package com.netcracker.atm.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Bills generated by hbm2java
 */
@Entity
@Table(name="bills"
    ,catalog="project"
)
public class Bills  implements java.io.Serializable {


     private int value;
     private int count;

    public Bills() {
    }

    public Bills(int value, int count) {
       this.value = value;
       this.count = count;
    }
   
     @Id 

    
    @Column(name="value", unique=true, nullable=false)
    public int getValue() {
        return this.value;
    }
    
    public void setValue(int value) {
        this.value = value;
    }

    
    @Column(name="count", nullable=false)
    public int getCount() {
        return this.count;
    }
    
    public void setCount(int count) {
        this.count = count;
    }




}


